### ISSUE TITLE
Some tournaments not parsing results properly

### ISSUE THREAD

**Issue by derekcorreia** [edgiardina/IfpaMaui#57]
Video showing issue: https://youtube.com/shorts/qz2sAEQSF44?feature=share
iOS 16.4, app store release as of 4/5/2023

Navigating to some tournament/league results in IFPA app do not show details or results, though they are available in the IFPA site. 
Events from the demonstration video: 
 * https://www.ifpapinball.com/tournaments/view.php?t=57234
 * https://www.ifpapinball.com/tournaments/view.php?t=60498

I'm unsure how to pull logs from the app, so unable to include here.
My guess at what's happening: Tournament Director is "Brian O'Neill" on both events, the apostrophe might not be properly escaped, and it's breaking the parser? Unsure.

**Comment by edgiardina** [comment]
Events are not logged in the app. But I've found the issue. The IFPA API is returning an error for this endpoint:

https://api.ifpapinball.com/v2/tournament/60498

`{"error":{"text":SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '')' at line 1}}`

I'll report it to Brian Shepherd

**Comment by edgiardina** [comment]
Brian has applied a fix for this, and I confirmed the tournaments are loading correctly.
